# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='city',
            field=models.CharField(default='a', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
