# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20161120_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='time',
            field=models.TimeField(default='2:5', verbose_name='Conversation Time'),
            preserve_default=False,
        ),
    ]
