# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmap_id', models.CharField(max_length=50)),
                ('mosque_name', models.CharField(max_length=100)),
                ('long_location', models.FloatField()),
                ('lat_location', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer', models.CharField(max_length=10)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Mosques')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='timing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.User'),
        ),
    ]
